param_sep: ';'
title: Refuge
default_lang: en
author:
  name: 'Arthur Finkler'
  email: refugethegame@gmail.com
taxonomies:
  - category
  - tag
metadata:
  abstract: 'Refuge, the Game that simulates a journey of refugees trying to escape for their lives.'
  summary: 'Refuge, the Game that simulates a journey of refugees trying to escape for their lives.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
